#:schema node_modules/wrangler/config-schema.json
main = ".open-next/worker.js"
name = "rambam-daily"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Custom domain
routes = [
  { pattern = "rambam.meir.pro", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
